name: Package and Release

on:
  push:
    tags:
      - 'v*' # Utløses bare når du pusher en "Tag" som starter på "v" (f.eks. v1.0.0)

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Nødvendig for å hente alle tags

      - name: Package and upload
        uses: BigWigsMods/packager@v2
        with:
          args: -w ${{ secrets.WAGO_API_TOKEN }}